# Generated by Django 4.2.13 on 2024-05-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
